
name: Build Forge Mod (1.20.1)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build
        run: gradle build --no-daemon
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: medicalmod-jar
          path: build/libs/*.jar
