name: Build Forge Mod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Repository auschecken
      - name: Checkout repository
        uses: actions/checkout@v4

      # Java 17 installieren (Forge 1.20.1 braucht Java 17)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Gradle Wrapper Berechtigungen setzen
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Mod bauen
      - name: Build with Gradle
        run: ./gradlew build

      # Mod .jar hochladen als Artefakt
      - name: Upload Mod Artifact
        uses: actions/upload-artifact@v4
        with:
          name: forge-mod
          path: build/libs/*.jar


