name: Build Forge Mod

# Workflow wird bei Push oder Pull-Request auf main ausgelöst
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest   # Immer neuester GitHub Actions Runner
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up JDK 17 (Temurin)
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for Gradle
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload Forge Mod Jar
      uses: actions/upload-artifact@v3
      with:
        name: forge-mod-1.20.1
        path: build/libs/*.jar

